"""
gui.py

Gradio-based GUI for creating dialogues, previewing, exporting JSON, uploading JSON, and generating audiobook.
"""
import gradio as gr
import os
import logging
import re
from datetime import datetime
from typing import List, Dict, Any
from TTS.api import TTS
from tts_engine import TTSEngine
from audio_utils import change_speed, change_volume, make_pause, merge_segments, save_audio, temp_filename
from json_utils import save_dialogues, load_dialogues, apply_defaults, chunk_text
from tqdm import tqdm

logger = logging.getLogger(__name__)

# Simple in-memory dialogue store
DIALOGUES: List[Dict[str, Any]] = []

# Cache engines per model to avoid reloads
ENGINE_CACHE: Dict[str, TTSEngine] = {}
MODEL_LIST_CACHE: List[str] = []

PREVIEW_DIR = os.path.join("outputs", "previews")
DEFAULT_PREVIEW_TEXT = "Hello, this is a quick voice preview generated by Coqui TTS."

def get_engine(model_name: str = None) -> TTSEngine:
    key = model_name or "__default__"
    if key not in ENGINE_CACHE:
        ENGINE_CACHE[key] = TTSEngine(model_name=model_name)
    return ENGINE_CACHE[key]


def ensure_preview_dir() -> str:
    os.makedirs(PREVIEW_DIR, exist_ok=True)
    print(f"Ensured preview directory exists at: {os.path.abspath(PREVIEW_DIR)}")
    return PREVIEW_DIR


def list_preview_files() -> List[str]:
    ensure_preview_dir()
    print(f"Listing preview files in: {os.path.abspath(PREVIEW_DIR)}")
    files = [f for f in os.listdir(PREVIEW_DIR) if f.lower().endswith(".wav")]
    print(f"Found {len(files)} preview files before sorting.")
    files.sort(key=lambda x: os.path.getmtime(os.path.join(PREVIEW_DIR, x)), reverse=True)
    print(f"Found {len(files)} preview files. {files[0] if files else 'No previews found.'}")
    return files


def preview_file_path(filename: str) -> str:
    if not filename:
        return ""
    return os.path.abspath(os.path.join(PREVIEW_DIR, filename))


def sanitize_name(name: str) -> str:
    if not name:
        return "voice"
    return re.sub(r"[^a-zA-Z0-9._-]+", "_", name)


def available_models() -> List[str]:
    global MODEL_LIST_CACHE
    if MODEL_LIST_CACHE:
        return MODEL_LIST_CACHE
    try:
        model_api = TTS()
        models = model_api.list_models()
        if isinstance(models, list):
            MODEL_LIST_CACHE = sorted(models)
            return MODEL_LIST_CACHE
        # Coqui 0.27+ may return a ModelManager object.
        if hasattr(models, "list_tts_models"):
            listed = models.list_tts_models()
            if isinstance(listed, list):
                MODEL_LIST_CACHE = sorted(listed)
                return MODEL_LIST_CACHE
    except Exception:
        logger.exception("Could not list Coqui TTS models")
    MODEL_LIST_CACHE = []
    return MODEL_LIST_CACHE


def refresh_available_models() -> List[str]:
    global MODEL_LIST_CACHE
    MODEL_LIST_CACHE = []
    return available_models()


def add_dialogue(speaker: str, text: str, speed: float = 1.0, volume: float = 1.0, pause_after: int = 0, emotion: str = None):
    if not text:
        return "Dialogue text is required.", DIALOGUES
    item = {
        "speaker": speaker,
        "text": text,
        "speed": speed,
        "volume": volume,
        "pause_after": pause_after
    }
    if emotion:
        item["emotion"] = emotion
    DIALOGUES.append(item)
    return "Added.", DIALOGUES


def clear_dialogues():
    global DIALOGUES
    DIALOGUES = []
    return DIALOGUES


def preview_dialogue(idx: int, model_name: str = None):
    if idx < 0 or idx >= len(DIALOGUES):
        return None
    item = DIALOGUES[idx]
    engine = get_engine(model_name)
    seg = engine.synthesize(item["text"], speaker=item.get("speaker"))
    seg = change_speed(seg, item.get("speed", 1.0))
    seg = change_volume(seg, item.get("volume", 1.0))
    # save to temp
    tmp = temp_filename()
    seg.export(tmp, format="wav")
    return tmp


def export_json(filename: str = "dialogues.json"):
    path = os.path.abspath(filename)
    save_dialogues(DIALOGUES, path)
    return f"Saved to {path}"


def generate_audiobook_from_json(json_path: str, out_path: str = "final_story.wav", model_name: str = None):
    engine = get_engine(model_name)
    dialogues = load_dialogues(json_path)
    segments = []
    total = len(dialogues)
    for item in tqdm(dialogues, desc="Dialogues"):
        if not apply_defaults(item):
            logger.error("Invalid dialogue item: %s", item)
            continue
        item = apply_defaults(item)
        chunks = chunk_text(item["text"])  # list of strings
        for c in chunks:
            try:
                seg = engine.synthesize(c, speaker=item.get("speaker"))
                seg = change_speed(seg, item.get("speed", 1.0))
                seg = change_volume(seg, item.get("volume", 1.0))
                if item.get("pause_after", 0) > 0:
                    seg += make_pause(item.get("pause_after"))
                segments.append(seg)
            except Exception as e:
                logger.exception("TTS failed for chunk")
    final = merge_segments(segments)
    save_audio(final, out_path)
    return os.path.abspath(out_path)


def build_gradio_app():
    ensure_preview_dir()
    initial_models = ['tts_models/en/vctk/vits'] + available_models()
    initial_model = initial_models[0] if initial_models else None
    initial_previews = ['p376.wav'] + list_preview_files()
    initial_preview = initial_previews[0] if initial_previews else None
    print(f"Initial preview files: {initial_preview}")

    with gr.Blocks(title="Advanced TTS Audiobook Generator") as demo:
        gr.Markdown("# Advanced TTS Audiobook Generator")
        gr.Markdown("Create dialogues, pick models/speakers from dropdowns, preview voices, and generate final audio.")

        with gr.Row():
            with gr.Column(scale=3):
                model_name = gr.Dropdown(
                    choices=initial_models,
                    value=initial_model,
                    label="TTS Model",
                    info="Select an available Coqui TTS model",
                    interactive=True,
                )
                refresh_models_btn = gr.Button("Refresh Models")
                speaker = gr.Dropdown(
                    choices=[],
                    value=None,
                    label="Speaker",
                    info="Populated after model selection",
                    interactive=False,
                )
                model_status = gr.Textbox(label="Model Status", lines=2, interactive=False)

            with gr.Column(scale=2):
                preview_file_dd = gr.Dropdown(
                    choices=initial_previews,
                    value=initial_preview,
                    label="Saved Voice Previews",
                    interactive=True,
                )
                preview_audio_player = gr.Audio(
                    value=preview_file_path(initial_preview) if initial_preview else None,
                    label="Preview Player",
                    type="filepath",
                )

        with gr.Tabs():
            with gr.Tab("Dialogue Builder"):
                with gr.Row():
                    with gr.Column(scale=2):
                        text = gr.Textbox(label="Dialogue text", lines=6)
                        with gr.Row():
                            speed = gr.Slider(minimum=0.5, maximum=2.0, value=1.0, step=0.05, label="Speed")
                            volume = gr.Slider(minimum=0.0, maximum=2.0, value=1.0, step=0.05, label="Volume")
                            pause_after = gr.Number(value=0, label="Pause after (ms)")
                        with gr.Row():
                            add_btn = gr.Button("Add Dialogue", variant="primary")
                            clear_btn = gr.Button("Clear Dialogues")
                        preview_text = gr.Textbox(
                            label="Voice Preview Text",
                            lines=2,
                            value=DEFAULT_PREVIEW_TEXT,
                        )
                        preview_selected_btn = gr.Button("Preview Selected Voice")

                    with gr.Column(scale=1):
                        preview_btn = gr.Button("Preview Last")
                        preview_audio = gr.Audio(label="Preview", type="filepath")
                        export_name = gr.Textbox(value="dialogues.json", label="Export filename")
                        export_btn = gr.Button("Export JSON")

                list_out = gr.Dataframe(
                    headers=["speaker", "text", "speed", "volume", "pause_after"],
                    interactive=False,
                    label="Current dialogues",
                )

            with gr.Tab("Generate From JSON"):
                upload = gr.File(label="Upload JSON")
                outpath = gr.Textbox(value="final_story.wav", label="Output filename")
                gen_btn = gr.Button("Generate Audiobook", variant="primary")
                
            with gr.Tab("Generate Voice from Text"):
                gr.Markdown("Use the Speaker dropdown above.")
                text_input = gr.Textbox(label="Input text for voice preview", lines=4)
                with gr.Row():
                    preview_text_btn = gr.Button("Generate Voice Preview", variant="primary")
                text_output = gr.Textbox(label="Status", interactive=False)
                text_audio_output = gr.Audio(label="Generated Audio", type="filepath")
                
            with gr.Tab("Generate Voice from Text File"):
                gr.Markdown("Use the Speaker dropdown above.")
                file_input = gr.File(label="Upload text file for voice preview")
                with gr.Row():
                    preview_file_btn = gr.Button("Generate Voice Preview from File", variant="primary")
                file_output_status = gr.Textbox(label="Status", interactive=False)
                file_audio_output = gr.Audio(label="Generated Audio", type="filepath")

        file_output = gr.Textbox(label="Status", lines=2)

        def _load_model_and_speakers(selected_model):
            if not selected_model:
                return (
                    gr.update(choices=[], value=None, interactive=False),
                    "No model selected.",
                )
            try:
                engine = get_engine(selected_model)
                speakers = engine.list_speakers() or []
                if len(speakers) > 1:
                    return (
                        gr.update(choices=speakers, value=speakers[0], interactive=True),
                        f"Model loaded: {selected_model} ({len(speakers)} speakers)",
                    )
                if len(speakers) == 1:
                    return (
                        gr.update(choices=speakers, value=speakers[0], interactive=False),
                        f"Model loaded: {selected_model} (single-speaker model)",
                    )
                return (
                    gr.update(choices=[], value=None, interactive=False),
                    f"Model loaded: {selected_model} (no explicit speaker list)",
                )
            except Exception as e:
                logger.exception("Model load failed")
                return (
                    gr.update(choices=[], value=None, interactive=False),
                    f"Failed to load model: {e}",
                )

        def _refresh_models():
            models = refresh_available_models()
            if not models:
                return (
                    gr.update(choices=[], value=None),
                    gr.update(choices=[], value=None, interactive=False),
                    "No models found. Ensure Coqui models are available.",
                )
            selected = models[0]
            speaker_update, status = _load_model_and_speakers(selected)
            return gr.update(choices=models, value=selected), speaker_update, status

        def _play_selected_preview(filename):
            if not filename:
                return None, "No preview selected."
            path = preview_file_path(filename)
            if not os.path.exists(path):
                return None, f"Preview file not found: {filename}"
            return path, f"Loaded preview: {filename}"

        def _generate_voice_preview(model_, speaker_, preview_text_):
            if not model_:
                return "Select a model first.", gr.update(choices=list_preview_files(), value=None), None
            sample_text = (preview_text_ or "").strip() or DEFAULT_PREVIEW_TEXT
            try:
                engine = get_engine(model_)
                seg = engine.synthesize(sample_text, speaker=speaker_ if speaker_ else None)
                ensure_preview_dir()
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                model_safe = sanitize_name(model_.split("/")[-1])
                speaker_safe = sanitize_name(speaker_ or "default")
                filename = f"{model_safe}__{speaker_safe}__{timestamp}.wav"
                out_path = os.path.join(PREVIEW_DIR, filename)
                seg.export(out_path, format="wav")

                files = list_preview_files()
                return (
                    f"Preview generated: {os.path.abspath(out_path)}",
                    gr.update(choices=files, value=filename),
                    os.path.abspath(out_path),
                )
            except Exception as e:
                logger.exception("Preview generation failed")
                files = list_preview_files()
                return f"Failed to generate preview: {e}", gr.update(choices=files, value=None), None

        def _add(speaker_, text_, speed_, volume_, pause_, model_):
            msg, data = add_dialogue(speaker_, text_, speed_, volume_, int(pause_), None)
            return msg, data

        def _clear():
            clear_dialogues()
            return "Cleared", []

        def _preview_last(model_):
            if not DIALOGUES:
                return "No dialogues to preview yet.", None
            audio_path = preview_dialogue(len(DIALOGUES) - 1, model_)
            if not audio_path:
                return "Preview failed.", None
            return "Preview ready.", audio_path

        def _gen(file, outp, model_):
            if not file:
                yield "No file uploaded"
                return
            path = file.name
            try:
                dialogues = load_dialogues(path)
            except Exception as e:
                yield f"Failed to read JSON: {e}"
                return

            total = len(dialogues)
            yield f"Starting generation: {total} dialogues"
            segments = []
            engine = get_engine(model_)
            i = 0
            for item in dialogues:
                i += 1
                yield f"Processing dialogue {i}/{total}"
                try:
                    item = apply_defaults(item)
                    chunks = chunk_text(item["text"])
                    for c in chunks:
                        seg = engine.synthesize(c, speaker=item.get("speaker"))
                        seg = change_speed(seg, item.get("speed", 1.0))
                        seg = change_volume(seg, item.get("volume", 1.0))
                        if item.get("pause_after", 0) > 0:
                            seg += make_pause(item.get("pause_after"))
                        segments.append(seg)
                except Exception as e:
                    yield f"Error synthesizing dialogue {i}: {e}"
            if not segments:
                yield "No audio generated."
                return
            yield "Merging segments..."
            final = merge_segments(segments)
            try:
                save_audio(final, outp)
                yield f"Saved audiobook to {os.path.abspath(outp)}"
            except Exception as e:
                yield f"Failed to save audio: {e}"

        def _generate_from_text(text_, model_, speaker_):
            if not model_:
                return "Select a model first.", None
            if not text_ or not text_.strip():
                return "Please enter some text.", None
            try:
                engine = get_engine(model_)
                seg = engine.synthesize(text_.strip(), speaker=speaker_ if speaker_ else None)
                ensure_preview_dir()
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                model_safe = sanitize_name(model_.split("/")[-1])
                speaker_safe = sanitize_name(speaker_ or "default")
                filename = f"text__{model_safe}__{speaker_safe}__{timestamp}.wav"
                out_path = os.path.join(PREVIEW_DIR, filename)
                seg.export(out_path, format="wav")
                return f"Audio generated: {os.path.abspath(out_path)}", os.path.abspath(out_path)
            except Exception as e:
                logger.exception("Text-to-speech generation failed")
                return f"Failed to generate audio: {e}", None

        def _generate_from_file(file_obj, model_, speaker_):
            if not model_:
                return "Select a model first.", None
            if not file_obj:
                return "Please upload a text file.", None
            try:
                with open(file_obj.name, 'r', encoding='utf-8') as f:
                    text = f.read().strip()
                if not text:
                    return "File is empty.", None
                engine = get_engine(model_)
                seg = engine.synthesize(text, speaker=speaker_ if speaker_ else None)
                ensure_preview_dir()
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                model_safe = sanitize_name(model_.split("/")[-1])
                speaker_safe = sanitize_name(speaker_ or "default")
                filename = f"file__{model_safe}__{speaker_safe}__{timestamp}.wav"
                out_path = os.path.join(PREVIEW_DIR, filename)
                seg.export(out_path, format="wav")
                return f"Audio generated from file: {os.path.abspath(out_path)}", os.path.abspath(out_path)
            except Exception as e:
                logger.exception("File-to-speech generation failed")
                return f"Failed to generate audio: {e}", None

        model_name.change(_load_model_and_speakers, inputs=[model_name], outputs=[speaker, model_status])
        refresh_models_btn.click(_refresh_models, outputs=[model_name, speaker, model_status])
        preview_file_dd.change(_play_selected_preview, inputs=[preview_file_dd], outputs=[preview_audio_player, file_output])
        preview_selected_btn.click(
            _generate_voice_preview,
            inputs=[model_name, speaker, preview_text],
            outputs=[file_output, preview_file_dd, preview_audio_player],
        )

        add_btn.click(_add, inputs=[speaker, text, speed, volume, pause_after, model_name], outputs=[file_output, list_out])
        clear_btn.click(_clear, outputs=[file_output, list_out])
        export_btn.click(lambda name: export_json(name), inputs=[export_name], outputs=[file_output])
        preview_btn.click(_preview_last, inputs=[model_name], outputs=[file_output, preview_audio])
        gen_btn.click(_gen, inputs=[upload, outpath, model_name], outputs=[file_output])
        preview_text_btn.click(_generate_from_text, inputs=[text_input, model_name, speaker], outputs=[text_output, text_audio_output])
        preview_file_btn.click(_generate_from_file, inputs=[file_input, model_name, speaker], outputs=[file_output_status, file_audio_output])

        if initial_model:
            demo.load(_load_model_and_speakers, inputs=[model_name], outputs=[speaker, model_status])
        else:
            demo.load(lambda: "No models found. Install/verify Coqui TTS models.", outputs=[model_status])

        return demo


if __name__ == "__main__":
    app = build_gradio_app()
    app.launch()
